baseurl: "/"
languageCode: "en-us"
title: "My test website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Research
      url: "research/"
      weight: 2
    - name: Teaching
      url: "teaching/"
      weight: 3
    - name: blog
      url: "blog/"

params:
  description: ""
  footer: "&copy; [Xin Wang] {Year} | [Github](https://github.com/wangx23) "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
